dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

subscriptions:
  chainlink: ${CHAINLINK_SUBSCRIPTION_ID}

ipfs:
  overwrite_metadata: False
  upload_type: pinata # pinata | ipfs
  # these pinata keys can make 500 calls
  pinata_key: ${PINATA_API_KEY}
  pinata_secret: ${PINATA_API_SECRET}
  pinata_jwm: Bearer ${PINATA_JWT}

dependencies:
  # - <organizzation/repo>@<version> downloaded from GitHub
  - smartcontractkit/chainlink-brownie-contracts@0.6.0
  - smartcontractkit/chainlink@1.11.0
  - OpenZeppelin/openzeppelin-contracts@4.8.1

compiler:
  solc:
    remappings:
      - "@brownie-cl=smartcontractkit/chainlink-brownie-contracts@0.6.0"
      - "@chainlink=smartcontractkit/chainlink@1.11.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"

networks:
  default: development
  development:
    keyhash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    verify: False
  mainnet-fork:
    verify: False
  goerli:
    fau_token: "0xBA62BCfcAaFc6622853cca2BE6Ac7d845BC0f2Dc"
    weth_token: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
    btc_usd_feed: "0xA39434A63A52E749F02807ae27335515BA4b07F7"
    eth_usd_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    dai_usd_feed: "0x0d79df66BE487753B02D015Fb622DED7f0E9798d"
    eur_usd_feed: "0x21420f2Fa4082d4Bf023698bB574F7D510345260"
    verify: True
  arbitrum-testnet:
    fau_token: "0x0aEfFF0D9FA3d101A5FB38849218c386cdADD9E2"
    weth_token: "0xbbfb1D86E3637136A4ca544485f6e7AE3f065Da4"
    book_token: "0x7E526dd042790E71134C204fE74e38C84a181Dd3"
    price_token: "0x44465d81DD317B78c69D3d44379345a68dA550E2"
    order_book: "0x395F63b46E05717218b2CEF5EBa3536579CD8126"
    btc_usd_feed: "0x56a43EB56Da12C0dc1D972ACb089c06a5dEF8e69"
    eth_usd_feed: "0xd30e2101a97dcbAeBCBC04F14C3f624E67A35165"
    dai_usd_feed: "0xb113F5A928BCfF189C998ab20d753a47F9dE5A61"
    verify: True
